### ISSUE TITLE
Improved unreal lens

### ISSUE THREAD

**Issue by redraskal** [spyglass-search/lens-box#39]
The current Unreal Engine lens crawls every page for Unreal Engine 4 & 5. This should really be separated into two lenses for both major versions. On top of that, it also picked up multiple different languages when I personally crawled it. This leads to an extreme, unnecessary page count. Also, the duplicate documents in foreign languages deteriorated the search quality.

Example of English-only Unreal Engine 5 documentation: `https://docs.unrealengine.com/5.0/en-US/`

**Comment by a5huynh** [comment]
@redraskal should be fixed. I split the the versions and both are up and available in the index 🙂
